name:                playing-with-my-balls
version:             0.1.0.0
github:              "jpolchlo/playing-with-my-balls"
license:             BSD-3-Clause
author:              "jpolchlo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A simple simulation to learn FRP with Netwire

dependencies:
- base >= 4.7 && < 5
- netwire >= 5
- gloss >= 1.13
- lens >= 5.2
- transformers >= 0.5
- linear >= 1.18
- containers >= 0.6
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  playing-with-my-balls-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - playing-with-my-balls

tests:
  playing-with-my-balls-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - playing-with-my-balls
